import postgres from "postgres";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { parseTestDatabaseEnvironment } from "@/config/test_database_environment";

const ids = Object.fromEntries(["publishedA","publishedB","draft","eligible","inactive","unavailable","demo","other","draftVehicle","lead"].map((key) => [key, crypto.randomUUID()])) as Record<string,string>;
const suffix=crypto.randomUUID().slice(0,8); const slugA=`tenant-a-${suffix}`, slugB=`tenant-b-${suffix}`, slugDraft=`tenant-draft-${suffix}`;
describe("capability de intake tenant",()=>{ let sql:ReturnType<typeof postgres>;
 const runtime=async <T>(f:()=>Promise<T>)=>{await sql`set role lead_intake_runtime`;try{return await f();}finally{await sql`reset role`;}};
 beforeAll(async()=>{sql=postgres(parseTestDatabaseEnvironment(process.env).testDatabaseUrl,{max:1});await sql`insert into organizations(id,name,slug,storefront_status) values (${ids.publishedA},'A',${slugA},'published'),(${ids.publishedB},'B',${slugB},'published'),(${ids.draft},'D',${slugDraft},'draft')`;await sql`insert into vehicles(id,organization_id,brand,model,year,color,weekly_price_cents,status,operational_status,is_demo) values (${ids.eligible},${ids.publishedA},'M','Elegível',2024,'P',1,'available','active',false),(${ids.inactive},${ids.publishedA},'M','Inativo',2024,'P',1,'available','inactive',false),(${ids.unavailable},${ids.publishedA},'M','Indisponível',2024,'P',1,'rented','active',false),(${ids.demo},${ids.publishedA},'M','Demo',2024,'P',1,'available','active',true),(${ids.draftVehicle},${ids.draft},'M','Draft',2024,'P',1,'available','active',false),(${ids.other},${ids.publishedB},'M','Outro',2024,'P',1,'available','active',false)`});
 afterAll(async()=>{await sql`delete from rental_leads where id=${ids.lead}`;await sql`delete from vehicles where id = any(${[ids.eligible,ids.inactive,ids.unavailable,ids.demo,ids.draftVehicle,ids.other]}::uuid[])`;await sql`delete from organizations where id = any(${[ids.publishedA,ids.publishedB,ids.draft]}::uuid[])`;await sql.end()});
 it("resolve somente o par elegível e não expõe dados extras",async()=>{const ok=await runtime(()=>sql`select public.resolve_tenant_lead_intake(${slugA},${ids.eligible}::uuid) data`);expect(ok[0].data).toEqual({organization_id:ids.publishedA,vehicle_id:ids.eligible});for(const [slug,id] of [["ausente",ids.eligible],[slugDraft,ids.eligible],[slugDraft,ids.draftVehicle],[slugA,ids.other],[slugA,ids.demo],[slugA,ids.inactive],[slugA,ids.unavailable]])expect((await runtime(()=>sql`select public.resolve_tenant_lead_intake(${slug},${id}::uuid) data`))[0].data).toBeNull()});
 it("permite somente insert new do par published elegível",async()=>{await runtime(()=>sql`insert into rental_leads(id,operation_id,organization_id,vehicle_id,full_name,phone,city,has_definitive_license,status) values (${ids.lead},${crypto.randomUUID()},${ids.publishedA},${ids.eligible},'Pessoa','(12) 99999-9999','Cidade',true,'new')`);for(const [organization,vehicle,status] of [[ids.publishedB,ids.eligible,'new'],[ids.publishedA,ids.other,'new'],[ids.draft,ids.eligible,'new'],[ids.draft,ids.draftVehicle,'new'],[ids.publishedA,ids.demo,'new'],[ids.publishedA,ids.inactive,'new'],[ids.publishedA,ids.unavailable,'new'],[ids.publishedA,ids.eligible,'approved'],[ids.publishedA,null,'new']] as const)await runtime(()=>expect(sql`insert into rental_leads(id,operation_id,organization_id,vehicle_id,full_name,phone,city,has_definitive_license,status) values (${crypto.randomUUID()},${crypto.randomUUID()},${organization},${vehicle},'Pessoa','(12) 99999-9999','Cidade',true,${status})`).rejects.toThrow())});
 it("não amplia leitura, mutação ou capability para outros papéis",async()=>{await runtime(async()=>{await expect(sql`select id from rental_leads`).rejects.toThrow();expect(await sql`select id from organizations`).toEqual([]);expect(await sql`select id from vehicles`).toEqual([]);await expect(sql`update rental_leads set status='contacted'`).rejects.toThrow()});for(const role of ['anon','authenticated']){await sql.unsafe(`set role ${role}`);try{await expect(sql`select public.resolve_tenant_lead_intake(${slugA},${ids.eligible}::uuid)`).rejects.toThrow()}finally{await sql`reset role`;}}});
});
